#!/usr/bin/env node
/**
 * Merge manual sub-pattern classifications from _etl_scripts/churn_subpattern_overrides.json
 * into public/snapshots/churn_subpatterns.json (which is auto-generated by keyword
 * detection).
 *
 * Union semantics: a customer's final tag list = auto-detected tags ∪ manual override
 * tags, deduped. Manual overrides DO NOT remove auto-detected tags — if you want to
 * suppress an auto tag, add a `suppress_subpatterns` array (TODO when needed).
 *
 * Idempotent. Runs as a post-step of build_churn_subpatterns.mjs in refresh_all.
 */

import fs from 'node:fs';
import path from 'node:path';

const ROOT = '/Users/beaulewis/projects/2 - Allmoxy - CFO/allmoxy-saas-dashboard';
const SNAP = path.join(ROOT, 'public/snapshots/churn_subpatterns.json');
const OVERRIDES = path.join(ROOT, '_etl_scripts/churn_subpattern_overrides.json');

if (!fs.existsSync(SNAP)) {
  console.error(`No churn_subpatterns.json at ${SNAP} — run build_churn_subpatterns first.`);
  process.exit(1);
}
if (!fs.existsSync(OVERRIDES)) {
  console.log('No manual sub-pattern overrides on file — nothing to merge.');
  process.exit(0);
}

const snap = JSON.parse(fs.readFileSync(SNAP, 'utf8'));
const overrides = JSON.parse(fs.readFileSync(OVERRIDES, 'utf8'));

snap.customer_subpatterns = snap.customer_subpatterns || {};

let mergedNew = 0;
let mergedAdded = 0;
const newTaggedIds = [];

for (const o of overrides.overrides || []) {
  const key = String(o.allmoxy_customer_id);
  const existing = new Set(snap.customer_subpatterns[key] || []);
  const before = existing.size;
  for (const t of o.subpatterns || []) existing.add(t);
  const after = existing.size;
  if (before === 0 && after > 0) {
    newTaggedIds.push(o.allmoxy_customer_id);
    mergedNew++;
  } else if (after > before) {
    mergedAdded++;
  }
  snap.customer_subpatterns[key] = [...existing];
}

// Stamp the snapshot so the dashboard can show provenance
snap.manual_overrides_applied = {
  source: '_etl_scripts/churn_subpattern_overrides.json',
  updated_at: overrides.updated_at,
  added_by: overrides.added_by,
  newly_tagged_customers: mergedNew,
  added_tags_to_existing_customers: mergedAdded,
  newly_tagged_ids: newTaggedIds,
};

fs.writeFileSync(SNAP, JSON.stringify(snap, null, 2));
console.log(`Merged manual sub-pattern overrides:`);
console.log(`  ${mergedNew} customers newly tagged (had no tags before)`);
console.log(`  ${mergedAdded} customers got additional tags merged into existing`);
console.log(`  ${(overrides.overrides || []).length} override entries processed`);
if (overrides.untagged_with_hubspot_reason_only?.customer_ids?.length) {
  console.log(`  ${overrides.untagged_with_hubspot_reason_only.customer_ids.length} customers explicitly left untagged (HubSpot reason on file but no sub-pattern evidence yet)`);
}
