import { Fragment, useMemo, useState } from 'react';
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';
import Grid from '@mui/material/Grid';
import Paper from '@mui/material/Paper';
import Typography from '@mui/material/Typography';
import Stack from '@mui/material/Stack';
import Skeleton from '@mui/material/Skeleton';
import Alert from '@mui/material/Alert';
import Chip from '@mui/material/Chip';
import TextField from '@mui/material/TextField';
import MenuItem from '@mui/material/MenuItem';
import { ResponsiveContainer, ComposedChart, Bar, Line, XAxis, YAxis, CartesianGrid, Tooltip as RTooltip, Legend } from 'recharts';

import PageHeader from '../components/common/PageHeader';
import DrillDownPanel from '../components/common/DrillDownPanel';
import InfoIcon from '../components/common/InfoIcon';
import CustomerLink from '../components/common/CustomerLink';
import { useSheetTab } from '../hooks/useSheetTab';

// Snapshot written by _etl_scripts/build_revenue_recognition.mjs (accrual / invoice basis,
// with a MONTH-END collection cutoff so Stripe reconciles to the bank).
type MonthRow = {
  recognized: number;               // billed = earned, by service period
  cash: number;                     // charge basis (reference)
  collected_in_period: number;      // cleared by month-end, this month's service
  outstanding_at_period_end: number;// billed this month, NOT cleared by month-end (new AR)
  collected_after_period: number;   // of this month's billings, collected in a later month
  still_open: number;               // of this month's billings, never collected yet
  prior_ar_collected: number;       // cash received THIS month for prior months' AR
  cash_received: number;            // collected_in_period + prior_ar_collected → bank deposits
};
type ArRow = { allmoxy_customer_id: number | null; name: string; invoice_id: string | null; invoice_date: string; service_month: string; amount: number; status: 'open' | 'uncollectible'; age_days: number; collectible?: boolean };
type DetailRow = { allmoxy_customer_id: number; name: string; month: string; basis: 'invoice' | 'charge'; recognized: number; collected_in_period: number; collected_after_period: number; still_open: number; outstanding_at_period_end: number };
// Full QuickBooks entry generated by the engine — mirrors Beau's Stripe entry + tax + accrual.
type JeLine = { account: string; debit: number | null; credit: number | null; description: string; group: 'cash' | 'tax' | 'accrual' };
type BalanceReport = { period_tz: string; starting_balance: number | null; charges_gross: number; refunds: number; connect_earnings: number; connect_refunds: number; stripe_fees: number; other_activity: number; net_activity: number; payouts: number; ending_balance: number | null; anchored: boolean };
type ArDetailRow = { allmoxy_customer_id: number | null; name: string; invoice_id: string | null; invoice_date: string; amount: number; tax: number; status: string; paid_at: string | null; resolution?: string };
type ArDetail = { new_ar_rows: ArDetailRow[]; prior_ar_rows: ArDetailRow[]; new_ar_ex_tax: number; new_ar_tax: number; prior_ar_collected: number; residual: number; total: number };
type JournalEntry = {
  lines: JeLine[]; debits: number; credits: number; balanced: boolean; memo: string[];
  balance_report?: BalanceReport;
  ar_detail?: ArDetail;
  inputs: { recognized_ex_tax: number; recognized_invoice_basis: number; direct_subscription_charges: number; direct_rows: Array<{ name: string; amount: number; desc: string; mapped: boolean }>; accrual_adjustment: number; tax_total_used: number; tax_basis_used: string; tax_by_state_invoice: Record<string, number>; tax_by_state_cash: Record<string, number>; annual_deferred_memo: number; balance_txn_rows: number; subscription_gross: number };
};
type Snap = {
  fetchedAt: string; invoices_fetched_at: string | null; basis: string; books_go_live: string; reconcile_from: string;
  months: string[]; by_month: Record<string, MonthRow>; ar_aging: ArRow[]; ar_total: number;
  reconciliation_detail: DetailRow[]; orphan_stripe_customers: Array<{ stripe_customer: string; months: string[]; latest_mrr: number }>;
  data_quality?: { invoices_missing_paid_at: number };
  journal_entries?: Record<string, JournalEntry>;
  ar_policy?: { writeoff_after_days: number | null; open_total: number; open_count: number; written_off_total: number; written_off_count: number; note: string } | null;
  ar_total_including_written_off?: number;
  balance_transactions_fetched_at?: string | null;
};

const USD0 = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 });
const USD2 = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', minimumFractionDigits: 2, maximumFractionDigits: 2 });
const USD_COMPACT = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', notation: 'compact', maximumFractionDigits: 1 });
function monthLabel(iso: string) { const [y, m] = iso.split('-').map(Number); return new Date(y, m - 1, 1).toLocaleDateString('en-US', { month: 'short', year: 'numeric' }); }
function fmtDate(iso: string | null | undefined) { if (!iso) return '—'; const [y, m, d] = String(iso).slice(0, 10).split('-'); return `${m}/${d}/${y}`; }
const TT = { contentStyle: { background: '#161B22', border: '1px solid #21262D', borderRadius: 6, color: '#FFFFFF' }, labelStyle: { color: '#FFFFFF' }, itemStyle: { color: '#FFFFFF' } };
const money = (v: number, signed = false) => `${signed && v > 0 ? '+' : ''}${v < 0 ? '−' : ''}${USD2.format(Math.abs(v))}`;

export default function RevenueRecognition() {
  const { data, isLoading, error } = useSheetTab('revenue_recognition');
  const snap = data as unknown as Snap | undefined;

  const currentMonth = useMemo(() => new Date().toISOString().slice(0, 7), []);
  const reconMonths = useMemo(() => (snap?.months ?? []).filter((m) => m >= (snap?.reconcile_from ?? '2026-01') && m < currentMonth), [snap, currentMonth]);
  const [month, setMonth] = useState<string>('');
  const selMonth = month || reconMonths[reconMonths.length - 1] || '';
  const row = selMonth ? snap?.by_month[selMonth] : undefined;
  const isPreGoLive = !!(snap && selMonth && selMonth < snap.books_go_live);

  const detailRows = useMemo(() => (snap?.reconciliation_detail ?? []).filter((d) => d.month === selMonth).sort((a, b) => b.outstanding_at_period_end - a.outstanding_at_period_end || b.recognized - a.recognized), [snap, selMonth]);
  const outstandingRows = useMemo(() => detailRows.filter((d) => d.outstanding_at_period_end > 0), [detailRows]);
  const arRows = useMemo(() => (snap?.ar_aging ?? []).slice().sort((a, b) => b.amount - a.amount), [snap]);
  const trend = useMemo(() => (snap?.months ?? []).filter((m) => m < currentMonth).slice(-24).map((m) => { const b = snap!.by_month[m]; return { month: m, Recognized: b.recognized, 'Cash received (bank)': b.cash_received, 'New AR (uncollected at month-end)': b.outstanding_at_period_end }; }), [snap, currentMonth]);

  // Net accrual adjustment = recognized − cash received = new AR − prior AR collected.
  const netAdj = row ? row.recognized - row.cash_received : 0;
  // The 1200 AR line in the generated entry expands to show what makes it up.
  const [arOpen, setArOpen] = useState(false);
  const isArLine = (l: JeLine) => l.group === 'accrual' && l.account.startsWith('1200');

  return (
    <Box>
      <PageHeader
        title="Revenue Recognition"
        subtitle="Accrual (invoice-basis) subscription revenue — what was billed by service period — with a month-end collection cutoff so Stripe reconciles to the bank. Drives the monthly QuickBooks journal entry and the AR aging you handle case-by-case."
        question="durable"
      />
      {error && <Alert severity="error" sx={{ mb: 2 }}>Failed to load revenue_recognition — {String(error)}</Alert>}

      <Stack direction="row" spacing={1} alignItems="center" flexWrap="wrap" useFlexGap sx={{ mb: 2 }}>
        <Chip size="small" label={`Books basis go‑live: ${snap ? monthLabel(snap.books_go_live + '-01') : '—'}`} sx={{ bgcolor: 'rgba(44,115,255,0.12)', color: 'primary.main', fontWeight: 600 }} />
        <Chip size="small" label="Recognize by invoice date · collected if paid by month‑end" sx={{ bgcolor: 'rgba(139,148,158,0.12)' }} />
        <Chip size="small" label={`Invoices synced ${snap?.invoices_fetched_at ? fmtDate(snap.invoices_fetched_at) : '—'}`} sx={{ bgcolor: 'rgba(139,148,158,0.12)' }} />
        <Box sx={{ flexGrow: 1 }} />
        <TextField select size="small" label="Month" value={selMonth} onChange={(e) => setMonth(e.target.value)} sx={{ minWidth: 170 }} disabled={!reconMonths.length}>
          {reconMonths.slice().reverse().map((m) => <MenuItem key={m} value={m}>{monthLabel(m + '-01')}</MenuItem>)}
        </TextField>
      </Stack>

      {isPreGoLive && (
        <Alert severity="info" sx={{ mb: 2 }}>
          <strong>{selMonth ? monthLabel(selMonth + '-01') : ''} is before the {snap ? monthLabel(snap.books_go_live + '-01') : ''} go‑live.</strong> These figures are reference only; from {snap ? monthLabel(snap.books_go_live + '-01') : ''} forward this is the operating basis for the books.
        </Alert>
      )}
      {!!snap?.data_quality?.invoices_missing_paid_at && (
        <Alert severity="warning" sx={{ mb: 2 }}>{snap.data_quality.invoices_missing_paid_at} paid invoice(s) lack a Stripe paid date; they're assumed collected in their invoice month. Re‑run the invoice sync to clear this.</Alert>
      )}

      {/* Full QuickBooks journal entry — mirrors Beau's monthly Stripe entry line-for-line,
          plus sales tax by state and the accrual adjustment. Rendered when the balance-
          transactions feed has the month; otherwise the Accrual bridge above stands alone. */}
      {(() => {
        const je = snap?.journal_entries?.[selMonth];
        if (!je) return null;
        const groupLabel: Record<JeLine['group'], string> = { cash: 'Stripe activity — your existing entry (ties to the Stripe API to the penny)', tax: 'Sales tax by state — backed out of 4000 into the payable accounts', accrual: 'Accrual adjustment — invoice basis (1200 AR ↔ 4000)' };
        const exportCsv = () => {
          const rows = [['#', 'Account', 'Debits', 'Credits', 'Description'], ...je.lines.map((l, i) => [String(i + 1), l.account, l.debit != null ? l.debit.toFixed(2) : '', l.credit != null ? l.credit.toFixed(2) : '', l.description])];
          rows.push(['', 'Totals', je.debits.toFixed(2), je.credits.toFixed(2), je.balanced ? 'Balanced' : 'OUT OF BALANCE']);
          const csv = rows.map((r) => r.map((v) => `"${String(v).replace(/"/g, '""')}"`).join(',')).join('\n');
          const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); a.download = `qb_journal_entry_${selMonth}.csv`; a.click(); URL.revokeObjectURL(a.href);
        };
        let lastGroup: string = '';
        const cell = { py: 0.6, px: 1, fontVariantNumeric: 'tabular-nums', borderBottom: '1px solid rgba(139,148,158,0.15)', fontSize: 13 } as const;
        return (
          <Paper sx={{ p: 3, mb: 3, borderLeft: '3px solid', borderColor: 'success.main' }}>
            <Stack direction="row" spacing={1} alignItems="center" flexWrap="wrap" useFlexGap sx={{ mb: 0.5 }}>
              <Typography variant="h6" sx={{ fontWeight: 500 }}>QuickBooks journal entry · {monthLabel(selMonth + '-01')}</Typography>
              <InfoIcon info={<><strong>What it is:</strong> Your complete monthly Stripe entry, generated from Stripe's balance transactions (the same data as the itemized-balance export), with the two additions you needed: <em>sales tax by state</em> and the <em>accrual adjustment</em>. Post it as-is.<br /><br /><strong>Structure:</strong> the Stripe-activity block is your existing entry line-for-line; refunds are classified by the refunded charge's type (subscription → 4000, Connect → 4200); 4000 is credited gross incl. tax and 4050 backs the tax out into 2141/2142/2144; the accrual lines move 4000 to recognized (invoice-basis) revenue and set up / relieve 1200 AR.<br /><br /><strong>Not in this entry:</strong> 4100 Annual Deferred Monthly (B&B Door, Mid Michigan) — you book that separately; shown as a memo so the P&amp;L ties.</>} />
              <Box sx={{ flexGrow: 1 }} />
              <Chip size="small" label={je.balanced ? `Balanced · ${USD2.format(je.debits)}` : `OUT OF BALANCE · Dr ${USD2.format(je.debits)} / Cr ${USD2.format(je.credits)}`} sx={{ fontWeight: 600, bgcolor: je.balanced ? 'rgba(46,160,67,0.14)' : 'rgba(229,72,77,0.16)', color: je.balanced ? 'success.main' : 'error.main' }} />
              <Button size="small" variant="outlined" onClick={exportCsv}>Export CSV</Button>
            </Stack>
            <Typography variant="caption" sx={{ color: 'text.secondary', display: 'block', mb: 1.5 }}>
              {je.lines.length} lines · built from {je.inputs.balance_txn_rows.toLocaleString()} Stripe balance transactions · recognized subscription revenue (ex‑tax) {USD2.format(je.inputs.recognized_ex_tax)} · accrual adjustment {money(je.inputs.accrual_adjustment, true)} · sales tax on the {je.inputs.tax_basis_used} basis {USD2.format(je.inputs.tax_total_used)}
            </Typography>
            <Box sx={{ overflowX: 'auto' }}>
              <Box component="table" sx={{ borderCollapse: 'collapse', width: '100%', minWidth: 720 }}>
                <thead>
                  <tr>
                    <Box component="th" sx={{ ...cell, textAlign: 'left', color: 'text.secondary', fontWeight: 600, width: 36 }}>#</Box>
                    <Box component="th" sx={{ ...cell, textAlign: 'left', color: 'text.secondary', fontWeight: 600 }}>Account</Box>
                    <Box component="th" sx={{ ...cell, textAlign: 'right', color: 'text.secondary', fontWeight: 600, width: 130 }}>Debits</Box>
                    <Box component="th" sx={{ ...cell, textAlign: 'right', color: 'text.secondary', fontWeight: 600, width: 130 }}>Credits</Box>
                    <Box component="th" sx={{ ...cell, textAlign: 'left', color: 'text.secondary', fontWeight: 600 }}>Description</Box>
                  </tr>
                </thead>
                <tbody>
                  {je.lines.map((l, i) => {
                    const showGroup = l.group !== lastGroup; lastGroup = l.group;
                    return (
                      <Fragment key={i}>
                        {showGroup && (
                          <tr><Box component="td" colSpan={5} sx={{ ...cell, pt: 1.5, color: l.group === 'accrual' ? 'primary.main' : l.group === 'tax' ? 'warning.main' : 'text.secondary', fontSize: 11, textTransform: 'uppercase', letterSpacing: '0.05em', fontWeight: 700, borderBottom: 'none' }}>{groupLabel[l.group]}</Box></tr>
                        )}
                        <tr
                          onClick={isArLine(l) ? () => setArOpen((v) => !v) : undefined}
                          style={isArLine(l) ? { cursor: 'pointer' } : undefined}
                        >
                          <Box component="td" sx={{ ...cell, color: 'text.secondary' }}>{i + 1}</Box>
                          <Box component="td" sx={{ ...cell, fontWeight: 500 }}>
                            {l.account}
                            {isArLine(l) && <Box component="span" sx={{ ml: 1, fontSize: 11, color: 'primary.main', fontWeight: 600 }}>{arOpen ? '▾ hide detail' : '▸ show detail'}</Box>}
                          </Box>
                          <Box component="td" sx={{ ...cell, textAlign: 'right' }}>{l.debit != null ? USD2.format(l.debit) : ''}</Box>
                          <Box component="td" sx={{ ...cell, textAlign: 'right' }}>{l.credit != null ? USD2.format(l.credit) : ''}</Box>
                          <Box component="td" sx={{ ...cell, color: 'text.secondary' }}>{l.description}</Box>
                        </tr>
                        {isArLine(l) && arOpen && je.ar_detail && (
                          <tr>
                            <Box component="td" colSpan={5} sx={{ ...cell, p: 0, borderBottom: 'none' }}>
                              <Box sx={{ m: 1, ml: 4, p: 1.5, borderRadius: 1, bgcolor: 'rgba(44,115,255,0.05)', border: '1px solid rgba(44,115,255,0.22)' }}>
                                <Typography variant="caption" sx={{ color: 'text.secondary', display: 'block', mb: 1 }}>
                                  What makes up the {USD2.format(je.ar_detail.total)}: invoices <strong>billed in {monthLabel(selMonth + '-01')} but unpaid at month‑end</strong> (incl. their sales tax), less <strong>prior‑month invoices collected this month</strong>.
                                </Typography>
                                <ArBridge d={je.ar_detail} />
                                <ArRowsTable title={`Billed in ${monthLabel(selMonth + '-01')}, unpaid at month-end → new AR`} rows={je.ar_detail.new_ar_rows} showResolution />
                                {!!je.ar_detail.prior_ar_rows.length && <ArRowsTable title="Prior-month invoices collected this month → relieves AR" rows={je.ar_detail.prior_ar_rows} negative />}
                                <Typography variant="caption" sx={{ color: 'text.secondary', display: 'block', mt: 1 }}>
                                  Every open invoice across all history is in the <strong>AR aging</strong> table further down the page ({snap ? USD0.format(snap.ar_total) : '—'} total).
                                </Typography>
                              </Box>
                            </Box>
                          </tr>
                        )}
                      </Fragment>
                    );
                  })}
                </tbody>
                <tfoot>
                  <tr>
                    <Box component="td" sx={{ ...cell, borderBottom: 'none' }} />
                    <Box component="td" sx={{ ...cell, fontWeight: 700, borderBottom: 'none', borderTop: '2px solid rgba(139,148,158,0.35)' }}>Totals</Box>
                    <Box component="td" sx={{ ...cell, textAlign: 'right', fontWeight: 700, borderBottom: 'none', borderTop: '2px solid rgba(139,148,158,0.35)' }}>{USD2.format(je.debits)}</Box>
                    <Box component="td" sx={{ ...cell, textAlign: 'right', fontWeight: 700, borderBottom: 'none', borderTop: '2px solid rgba(139,148,158,0.35)' }}>{USD2.format(je.credits)}</Box>
                    <Box component="td" sx={{ ...cell, borderBottom: 'none', borderTop: '2px solid rgba(139,148,158,0.35)', color: je.balanced ? 'success.main' : 'error.main', fontWeight: 600 }}>{je.balanced ? 'Balanced' : `Off by ${USD2.format(Math.abs(je.debits - je.credits))}`}</Box>
                  </tr>
                </tfoot>
              </Box>
            </Box>
            <Box sx={{ mt: 1.5 }}>
              {je.memo.map((m, i) => <Typography key={i} variant="caption" sx={{ color: 'text.secondary', display: 'block' }}>• {m}</Typography>)}
              <Typography variant="caption" sx={{ color: 'text.secondary', display: 'block' }}>
                • Direct/legacy subscription charges billed outside Stripe invoices (sandbox instances, extra domains, AI‑token upgrades) are included in both MRR and recognized revenue, so this figure matches the Revenue Waterfall's accrual ending MRR.
                {je.inputs.direct_subscription_charges > 0 && <> Of these, {USD2.format(je.inputs.direct_subscription_charges)} is from Stripe customers with no roster record ({je.inputs.direct_rows.filter((d) => !d.mapped).map((d) => `${d.name} ${USD0.format(d.amount)}`).join(', ')}) and is added here only — it can't sit on a per‑customer series until those customers exist.</>}
              </Typography>
            </Box>
            {je.balance_report && (() => {
              const b = je.balance_report;
              const row = (label: string, v: number | null, opts: { bold?: boolean; indent?: boolean; top?: boolean } = {}) => (
                <Stack direction="row" justifyContent="space-between" sx={{ py: 0.35, pl: opts.indent ? 2 : 0, borderTop: opts.top ? '1px solid rgba(139,148,158,0.3)' : 'none', fontWeight: opts.bold ? 700 : 400, fontSize: 13, fontVariantNumeric: 'tabular-nums' }}>
                  <span style={{ color: opts.bold ? undefined : '#8B949E' }}>{label}</span><span>{v == null ? '—' : money(v)}</span>
                </Stack>
              );
              return (
                <Box sx={{ mb: 2, p: 1.5, borderRadius: 1, bgcolor: 'rgba(139,148,158,0.06)', border: '1px solid rgba(139,148,158,0.18)', maxWidth: 520 }}>
                  <Stack direction="row" spacing={1} alignItems="center" sx={{ mb: 0.5 }}>
                    <Typography variant="caption" sx={{ color: 'text.secondary', textTransform: 'uppercase', letterSpacing: '0.05em', fontWeight: 700 }}>Stripe Balance report · {monthLabel(selMonth + '-01')} · US/Mountain</Typography>
                    <InfoIcon info={<><strong>What it is:</strong> The same frame as Stripe → Reports → Balance (merchant template): starting balance + activity − payouts = ending balance. Built from the identical balance transactions, so it should match the dashboard report line for line. <em>Payouts</em> is your DR 4200 gross-deposits line; <em>ending − starting</em> is your 1003 Stripe Account line.{!b.anchored && <><br /><br />Starting/ending balances appear once the sync captures the current Stripe balance (next refresh).</>}</>} />
                  </Stack>
                  {row('Starting balance', b.starting_balance, { bold: true })}
                  {row('Charges (gross)', b.charges_gross, { indent: true })}
                  {row('Refunds', b.refunds, { indent: true })}
                  {row('Connect platform earnings', b.connect_earnings, { indent: true })}
                  {b.connect_refunds !== 0 && row('Connect refunds', b.connect_refunds, { indent: true })}
                  {row('Stripe fees', b.stripe_fees, { indent: true })}
                  {b.other_activity !== 0 && row('Other activity', b.other_activity, { indent: true })}
                  {row('Net activity', b.net_activity, { top: true })}
                  {row('Payouts to bank', -b.payouts)}
                  {row('Ending balance', b.ending_balance, { bold: true, top: true })}
                </Box>
              );
            })()}
          </Paper>
        );
      })()}

      {/* KPI strip */}
      <Grid container spacing={2} sx={{ mb: 3 }}>
        <Grid item xs={12} sm={6} md={2.4}><Kpi label="Recognized (accrual)" value={row ? USD0.format(row.recognized) : null} hint="Billed by service period" color="primary.main" loading={isLoading} info={<><strong>What it is:</strong> Subscription revenue recognized in the month — every recurring invoice line <em>billed</em> in the month (invoice date), paid / open / uncollectible; void excluded. Annual invoices spread evenly across their term. This ties to Stripe's monthly invoice totals. Direct‑charge subscribers fall back to the charge basis.<br /><br /><strong>This is the revenue to recognize in QuickBooks.</strong></>} /></Grid>
        <Grid item xs={12} sm={6} md={2.4}><Kpi label="Collected in period" value={row ? USD0.format(row.collected_in_period) : null} hint="Paid by last day of month" color="success.main" loading={isLoading} info={<><strong>What it is:</strong> Of this month's billings, the amount whose Stripe payment cleared <em>on or before the last day of the month</em> — the reconciliation cutoff. Anything paid after that is AR at month‑end, even if it's paid today.</>} /></Grid>
        <Grid item xs={12} sm={6} md={2.4}><Kpi label="New AR at month‑end" value={row ? USD0.format(row.outstanding_at_period_end) : null} hint="Billed, not cleared by cutoff" color="warning.main" loading={isLoading} info={<><strong>What it is:</strong> Recognized − Collected in period: this month's billings that hadn't cleared by month‑end. This is the receivable to set up (DR AR / CR Revenue). It splits into <em>collected after period</em> (came in later) and <em>still open</em>.</>} /></Grid>
        <Grid item xs={12} sm={6} md={2.4}><Kpi label="Collected after period" value={row ? USD0.format(row.collected_after_period) : null} hint="Of this month's billings, paid later" loading={isLoading} info={<><strong>What it is:</strong> This month's billings that were paid in a <em>later</em> month. Recognized here; the cash lands in that later month's bank deposits and relieves AR there — it is <strong>never</strong> recognized twice.</>} /></Grid>
        <Grid item xs={12} sm={6} md={2.4}><Kpi label="Still open" value={row ? USD0.format(row.still_open) : null} hint="Never collected (as of today)" color={row && row.still_open > 0 ? 'error.main' : 'text.primary'} loading={isLoading} info={<><strong>What it is:</strong> This month's billings still unpaid today (open or uncollectible in Stripe). Your case‑by‑case list — retry, void, or mark uncollectible in Stripe and it flows through on the next refresh. No automatic write‑offs.</>} /></Grid>
      </Grid>

      {/* QuickBooks journal entry */}
      <Paper sx={{ p: 3, mb: 3, borderLeft: '3px solid', borderColor: 'primary.main' }}>
        <Stack direction="row" spacing={1} alignItems="center" sx={{ mb: 1.5 }}>
          <Typography variant="h6" sx={{ fontWeight: 500 }}>Accrual bridge · {selMonth ? monthLabel(selMonth + '-01') : '—'}</Typography>
          <InfoIcon info={<><strong>What it is:</strong> The monthly entry that moves subscription revenue from cash to accrual. Your bank deposits (already in QB) = <em>cash received</em>. Accrual revenue = <em>recognized</em>. The <strong>net</strong> adjustment is the change in AR: new receivables from this month's uncleared billings, less prior‑period receivables that were collected this month. Stripe is the system of record; the itemized table below is the audit support.</>} />
        </Stack>
        {!row ? <Skeleton variant="rectangular" height={140} /> : (
          <Grid container spacing={2}>
            <Grid item xs={12} md={7}>
              <Box component="table" sx={{ borderCollapse: 'collapse', width: '100%', '& td': { py: 0.55, fontVariantNumeric: 'tabular-nums' } }}>
                <tbody>
                  <tr><td>Recognized subscription revenue (accrual)</td><td style={{ textAlign: 'right', fontWeight: 600 }}>{USD2.format(row.recognized)}</td></tr>
                  <tr><td style={{ color: '#8B949E' }}>Less: cash received this month (bank deposits)</td><td style={{ textAlign: 'right', color: '#8B949E' }}>({USD2.format(row.cash_received)})</td></tr>
                  <tr><td style={{ color: '#8B949E', paddingLeft: 16, fontSize: 12 }}>· of which this month's billings collected in period</td><td style={{ textAlign: 'right', color: '#8B949E', fontSize: 12 }}>{USD2.format(row.collected_in_period)}</td></tr>
                  <tr><td style={{ color: '#8B949E', paddingLeft: 16, fontSize: 12 }}>· of which prior‑period AR collected this month</td><td style={{ textAlign: 'right', color: '#8B949E', fontSize: 12 }}>{USD2.format(row.prior_ar_collected)}</td></tr>
                  <tr style={{ borderTop: '1px solid #30363D' }}><td style={{ fontWeight: 700, paddingTop: 8 }}>Net accrual adjustment (Δ Accounts Receivable)</td><td style={{ textAlign: 'right', fontWeight: 700, paddingTop: 8, color: netAdj >= 0 ? '#2EA043' : '#F5A623' }}>{money(netAdj, true)}</td></tr>
                  <tr><td style={{ color: '#8B949E', paddingLeft: 16, fontSize: 12 }}>= new AR at month‑end {USD2.format(row.outstanding_at_period_end)} − prior AR collected {USD2.format(row.prior_ar_collected)}</td><td /></tr>
                </tbody>
              </Box>
            </Grid>
            <Grid item xs={12} md={5}>
              <Box sx={{ p: 1.5, borderRadius: 1, bgcolor: 'rgba(44,115,255,0.06)', border: '1px solid rgba(44,115,255,0.25)', fontSize: 13 }}>
                <Typography variant="caption" sx={{ color: 'text.secondary', textTransform: 'uppercase', letterSpacing: '0.05em', fontWeight: 700, display: 'block', mb: 0.5 }}>Suggested entry (net)</Typography>
                {netAdj >= 0 ? (
                  <><div><b>DR</b> Accounts Receivable · {USD2.format(netAdj)}</div><div style={{ paddingLeft: 24 }}><b>CR</b> Subscription Revenue · {USD2.format(netAdj)}</div></>
                ) : (
                  <><div><b>DR</b> Subscription Revenue · {USD2.format(Math.abs(netAdj))}</div><div style={{ paddingLeft: 24 }}><b>CR</b> Accounts Receivable · {USD2.format(Math.abs(netAdj))}</div></>
                )}
                <Typography variant="caption" sx={{ color: 'text.secondary', display: 'block', mt: 1 }}>
                  Or book gross: <b>DR AR / CR Revenue</b> {USD2.format(row.outstanding_at_period_end)} for new receivables, and <b>DR Cash / CR AR</b> {USD2.format(row.prior_ar_collected)} for prior receivables collected. Confirm account mapping with your accountant.
                </Typography>
              </Box>
            </Grid>
          </Grid>
        )}
      </Paper>

      {/* Reconciliation — what was supposed to process */}
      <Paper sx={{ p: 3, mb: 3 }}>
        <Stack direction="row" spacing={1} alignItems="center" sx={{ mb: 0.5 }}>
          <Typography variant="h6" sx={{ fontWeight: 500 }}>What was supposed to process · {selMonth ? monthLabel(selMonth + '-01') : '—'}</Typography>
          <InfoIcon info={<><strong>What it is:</strong> Every subscription recognized in the month, with its collection status at the month‑end cutoff: <em>collected in period</em> (cleared by month‑end), <em>outstanding at month‑end</em> (the AR to book), which then resolved as <em>collected after</em> or is <em>still open</em>.<br /><br /><strong>Basis:</strong> <em>invoice</em> = Stripe recurring invoices by service period; <em>charge</em> = direct‑charge subscriber (no invoice → only what cleared is known, nothing outstanding). CSV = audit support for the entry.</>} />
        </Stack>
        <Typography variant="caption" sx={{ color: 'text.secondary', display: 'block', mb: 1.5 }}>
          {detailRows.length} subscriptions · {outstandingRows.length} outstanding at month‑end ({USD0.format(outstandingRows.reduce((s, r) => s + r.outstanding_at_period_end, 0))}) · sorted by outstanding, then recognized
        </Typography>
        {isLoading ? <Skeleton variant="rectangular" height={300} /> : (
          <DrillDownPanel<Record<string, unknown>>
            title=""
            rows={detailRows as unknown as Array<Record<string, unknown>>}
            columns={[
              { key: 'name', label: 'Customer', render: (r: Record<string, unknown>) => { const d = r as unknown as DetailRow; return <CustomerLink id={d.allmoxy_customer_id} name={d.name} />; }, exportValue: (r: Record<string, unknown>) => (r as unknown as DetailRow).name, sortValue: (r: Record<string, unknown>) => (r as unknown as DetailRow).name },
              { key: 'basis', label: 'Basis', render: (r: Record<string, unknown>) => { const b = (r as unknown as DetailRow).basis; return <Chip size="small" label={b} sx={{ height: 20, fontSize: 11, bgcolor: b === 'invoice' ? 'rgba(44,115,255,0.12)' : 'rgba(245,166,35,0.14)', color: b === 'invoice' ? 'primary.main' : 'warning.main' }} />; } },
              { key: 'recognized', label: 'Recognized', align: 'right', render: (r: Record<string, unknown>) => USD2.format((r as unknown as DetailRow).recognized) },
              { key: 'collected_in_period', label: 'Collected in period', align: 'right', render: (r: Record<string, unknown>) => USD2.format((r as unknown as DetailRow).collected_in_period) },
              { key: 'outstanding_at_period_end', label: 'Outstanding at month‑end', align: 'right', render: (r: Record<string, unknown>) => { const v = (r as unknown as DetailRow).outstanding_at_period_end; return <span style={{ color: v > 0 ? '#F5A623' : '#8B949E', fontWeight: v > 0 ? 600 : 400 }}>{USD2.format(v)}</span>; } },
              { key: 'collected_after_period', label: 'Collected after', align: 'right', render: (r: Record<string, unknown>) => { const v = (r as unknown as DetailRow).collected_after_period; return <span style={{ color: v > 0 ? '#2EA043' : '#8B949E' }}>{USD2.format(v)}</span>; } },
              { key: 'still_open', label: 'Still open', align: 'right', render: (r: Record<string, unknown>) => { const v = (r as unknown as DetailRow).still_open; return <span style={{ color: v > 0 ? '#E5484D' : '#8B949E', fontWeight: v > 0 ? 600 : 400 }}>{USD2.format(v)}</span>; } },
            ]}
            filename={`revenue_recognition_${selMonth}`}
          />
        )}
      </Paper>

      {/* AR aging */}
      <Paper sx={{ p: 3, mb: 3 }}>
        <Stack direction="row" spacing={1} alignItems="center" sx={{ mb: 0.5 }}>
          <Typography variant="h6" sx={{ fontWeight: 500 }}>AR aging · open & uncollectible invoices</Typography>
          <InfoIcon info={<><strong>What it is:</strong> Every finalized‑unpaid Stripe invoice across all history, with its service month and age. Your case‑by‑case list — retry, void, or mark uncollectible in Stripe and it flows through on the next refresh. No automatic write‑offs.</>} />
        </Stack>
        <Typography variant="caption" sx={{ color: 'text.secondary', display: 'block', mb: 1.5 }}>
          {arRows.length} invoices · {snap ? USD0.format(snap.ar_total) : '—'} collectible · {arRows.filter((r) => r.status === 'uncollectible').length} flagged uncollectible in Stripe · sorted by amount
        </Typography>
        {snap?.ar_policy?.writeoff_after_days != null && (
          <Alert severity="info" sx={{ mb: 1.5 }}>
            <strong>Anything past {snap.ar_policy.writeoff_after_days} days is treated as closed.</strong>{' '}
            {USD0.format(snap.ar_policy.written_off_total)} across {snap.ar_policy.written_off_count} invoices is written off and excluded from the AR balance, leaving{' '}
            <strong>{USD0.format(snap.ar_policy.open_total)}</strong> collectible ({snap.ar_policy.open_count} invoices). Written-off rows are struck through below.
            <br /><br />
            These invoices are <strong>still open in Stripe</strong> — this is a reporting policy only. Void them or mark them uncollectible in Stripe to make it official. Revenue stays recognized (it was earned when billed); the write-off is a bad-debt expense, not a revenue reversal.
          </Alert>
        )}
        {isLoading ? <Skeleton variant="rectangular" height={300} /> : (
          <DrillDownPanel<Record<string, unknown>>
            title=""
            rows={arRows as unknown as Array<Record<string, unknown>>}
            columns={[
              { key: 'name', label: 'Customer', render: (r: Record<string, unknown>) => { const a = r as unknown as ArRow; return a.allmoxy_customer_id != null ? <CustomerLink id={a.allmoxy_customer_id} name={a.name} /> : <span>{a.name}</span>; }, exportValue: (r: Record<string, unknown>) => (r as unknown as ArRow).name, sortValue: (r: Record<string, unknown>) => (r as unknown as ArRow).name },
              { key: 'invoice_date', label: 'Invoice date', render: (r: Record<string, unknown>) => fmtDate((r as unknown as ArRow).invoice_date), sortValue: (r: Record<string, unknown>) => (r as unknown as ArRow).invoice_date },
              { key: 'service_month', label: 'Service month', render: (r: Record<string, unknown>) => monthLabel((r as unknown as ArRow).service_month + '-01'), sortValue: (r: Record<string, unknown>) => (r as unknown as ArRow).service_month },
              { key: 'amount', label: 'Amount', align: 'right', render: (r: Record<string, unknown>) => { const a = r as unknown as ArRow; const closed = a.collectible === false; return <span style={{ textDecoration: closed ? 'line-through' : undefined, color: closed ? '#8B949E' : undefined }}>{USD2.format(a.amount)}</span>; }, sortValue: (r: Record<string, unknown>) => (r as unknown as ArRow).amount },
              { key: 'status', label: 'Status', render: (r: Record<string, unknown>) => { const s = (r as unknown as ArRow).status; return <Chip size="small" label={s} sx={{ height: 20, fontSize: 11, bgcolor: s === 'open' ? 'rgba(245,166,35,0.14)' : 'rgba(229,72,77,0.14)', color: s === 'open' ? 'warning.main' : 'error.main' }} />; } },
              { key: 'age_days', label: 'Age (days)', align: 'right', render: (r: Record<string, unknown>) => { const a = r as unknown as ArRow; const closed = a.collectible === false; return <span style={{ color: closed ? '#8B949E' : undefined, fontWeight: closed ? 400 : 600 }}>{a.age_days}{closed ? ' · closed' : ''}</span>; }, sortValue: (r: Record<string, unknown>) => (r as unknown as ArRow).age_days },
            ]}
            filename="ar_aging_open_invoices"
          />
        )}
      </Paper>

      {/* Trend */}
      <Paper sx={{ p: 3, mb: 3 }}>
        <Stack direction="row" spacing={1} alignItems="center" sx={{ mb: 2 }}>
          <Typography variant="subtitle1" sx={{ fontWeight: 600 }}>Recognized vs cash received · trailing 24 months</Typography>
          <InfoIcon info={<><strong>What it is:</strong> Accrual revenue (line) against cash that actually reached the bank each month (dashed). Bars = new AR created that month (billings not cleared by month‑end). Where cash lags recognized, receivables are building; where it leads, prior receivables are being collected.</>} />
        </Stack>
        {isLoading ? <Skeleton variant="rectangular" height={280} /> : (
          <Box sx={{ height: 280 }}>
            <ResponsiveContainer>
              <ComposedChart data={trend} margin={{ top: 8, right: 16, left: 0, bottom: 0 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="rgba(139,148,158,0.12)" vertical={false} />
                <XAxis dataKey="month" tickFormatter={(m) => monthLabel(String(m) + '-01').replace(' 20', ' ’')} stroke="#8B949E" fontSize={10} interval={Math.max(0, Math.floor(trend.length / 8))} />
                <YAxis yAxisId="mrr" stroke="#8B949E" fontSize={10} width={56} tickFormatter={(v) => USD_COMPACT.format(Number(v))} />
                <YAxis yAxisId="ar" orientation="right" stroke="#8B949E" fontSize={10} width={48} tickFormatter={(v) => USD_COMPACT.format(Number(v))} />
                <RTooltip {...TT} labelFormatter={(m) => monthLabel(String(m) + '-01')} formatter={(v: number, n: string) => [USD0.format(v), n]} />
                <Legend wrapperStyle={{ fontSize: 11 }} />
                <Bar yAxisId="ar" dataKey="New AR (uncollected at month-end)" fill="rgba(245,166,35,0.45)" />
                <Line yAxisId="mrr" type="monotone" dataKey="Recognized" stroke="#2C73FF" strokeWidth={2.2} dot={false} />
                <Line yAxisId="mrr" type="monotone" dataKey="Cash received (bank)" stroke="#8B949E" strokeWidth={1.6} strokeDasharray="4 3" dot={false} />
              </ComposedChart>
            </ResponsiveContainer>
          </Box>
        )}
      </Paper>

      {!!snap?.orphan_stripe_customers?.length && (
        <Alert severity="warning">
          <strong>{snap.orphan_stripe_customers.length} Stripe customer{snap.orphan_stripe_customers.length === 1 ? '' : 's'} with invoices but no customer profile</strong> — counted in recognized totals but not in the per‑customer table until mapped (add to <code>stripe_id_overrides.json</code> or create the roster record): {snap.orphan_stripe_customers.map((o) => `${o.stripe_customer} (${USD0.format(o.latest_mrr)}/mo)`).join(' · ')}
        </Alert>
      )}
    </Box>
  );
}

// Δ AR bridge: new AR (ex-tax + tax) − prior AR collected + residual = posted line.
function ArBridge({ d }: { d: ArDetail }) {
  const line = (label: string, v: number, bold = false, top = false) => (
    <Stack key={label} direction="row" justifyContent="space-between" sx={{ py: 0.3, fontSize: 12.5, fontVariantNumeric: 'tabular-nums', fontWeight: bold ? 700 : 400, borderTop: top ? '1px solid rgba(139,148,158,0.3)' : 'none' }}>
      <span style={{ color: bold ? undefined : '#8B949E' }}>{label}</span><span>{money(v)}</span>
    </Stack>
  );
  return (
    <Box sx={{ maxWidth: 460, mb: 1.5 }}>
      {line(`New AR — billed, unpaid at month-end (${d.new_ar_rows.length} invoice${d.new_ar_rows.length === 1 ? '' : 's'})`, d.new_ar_ex_tax)}
      {line('New AR — sales tax on those invoices', d.new_ar_tax)}
      {line(`Less: prior-month AR collected this month (${d.prior_ar_rows.length})`, -d.prior_ar_collected)}
      {Math.abs(d.residual) >= 0.01 && line('Other timing / partial payments', d.residual)}
      {line('Δ Accounts Receivable (posted)', d.total, true, true)}
    </Box>
  );
}

function ArRowsTable({ title, rows, showResolution, negative }: { title: string; rows: ArDetailRow[]; showResolution?: boolean; negative?: boolean }) {
  const c = { py: 0.4, px: 0.75, fontSize: 12, borderBottom: '1px solid rgba(139,148,158,0.12)', fontVariantNumeric: 'tabular-nums' } as const;
  return (
    <Box sx={{ mb: 1.5 }}>
      <Typography variant="caption" sx={{ color: 'text.secondary', fontWeight: 700, display: 'block', mb: 0.5 }}>{title} · {rows.length}</Typography>
      <Box sx={{ overflowX: 'auto' }}>
        <Box component="table" sx={{ borderCollapse: 'collapse', width: '100%', minWidth: 560 }}>
          <thead><tr>
            {['Customer', 'Invoice date', 'Amount', 'Tax', 'Total', showResolution ? 'Status' : 'Paid'].map((h, i) => (
              <Box key={h} component="th" sx={{ ...c, textAlign: i >= 2 && i <= 4 ? 'right' : 'left', color: 'text.secondary', fontWeight: 600 }}>{h}</Box>
            ))}
          </tr></thead>
          <tbody>
            {rows.map((r, i) => (
              <tr key={i}>
                <Box component="td" sx={{ ...c }}>{r.allmoxy_customer_id != null ? <CustomerLink id={r.allmoxy_customer_id} name={r.name} /> : r.name}</Box>
                <Box component="td" sx={{ ...c, color: 'text.secondary' }}>{fmtDate(r.invoice_date)}</Box>
                <Box component="td" sx={{ ...c, textAlign: 'right' }}>{money(negative ? -r.amount : r.amount)}</Box>
                <Box component="td" sx={{ ...c, textAlign: 'right', color: 'text.secondary' }}>{r.tax ? money(negative ? -r.tax : r.tax) : '—'}</Box>
                <Box component="td" sx={{ ...c, textAlign: 'right', fontWeight: 600 }}>{money(negative ? -(r.amount + r.tax) : r.amount + r.tax)}</Box>
                <Box component="td" sx={{ ...c, color: r.resolution === 'still open' ? '#F5A623' : r.resolution === 'uncollectible' ? '#E5484D' : 'text.secondary' }}>{showResolution ? r.resolution : fmtDate(r.paid_at)}</Box>
              </tr>
            ))}
          </tbody>
        </Box>
      </Box>
    </Box>
  );
}

function Kpi({ label, value, hint, color = 'text.primary', loading, info }: { label: string; value: string | null; hint: string; color?: string; loading?: boolean; info?: React.ReactNode }) {
  return (
    <Paper sx={{ p: 2, height: '100%' }}>
      <Stack direction="row" justifyContent="space-between" alignItems="flex-start">
        <Typography variant="caption" sx={{ color: 'text.secondary', textTransform: 'uppercase', letterSpacing: '0.05em', fontSize: 10 }}>{label}</Typography>
        {info && <InfoIcon info={info} />}
      </Stack>
      {loading || value == null ? <Skeleton variant="text" width="60%" sx={{ fontSize: 24 }} /> : <Typography variant="h6" sx={{ fontWeight: 600, color, mt: 0.25, fontVariantNumeric: 'tabular-nums' }}>{value}</Typography>}
      <Typography variant="caption" sx={{ color: 'text.secondary', display: 'block', mt: 0.25, fontSize: 10 }}>{hint}</Typography>
    </Paper>
  );
}
